---
fixtures:
  repositories:
    augeasproviders_core: https://github.com/simp/augeasproviders_core
    augeasproviders_ssh: https://github.com/simp/augeasproviders_ssh
    concat: https://github.com/simp/puppetlabs-concat
    gitlab:
      repo: https://github.com/simp/puppet-gitlab.git
      ref: v3.0.2
    iptables: https://github.com/simp/pupmod-simp-iptables
    ntpd: https://github.com/simp/pupmod-simp-ntpd
    pam: https://github.com/simp/pupmod-simp-pam
    pki: https://github.com/simp/pupmod-simp-pki
    postfix: https://github.com/simp/pupmod-simp-postfix
    rsyslog: https://github.com/simp/pupmod-simp-rsyslog
    ssh: https://github.com/simp/pupmod-simp-ssh
    simplib: https://github.com/simp/pupmod-simp-simplib
    stdlib: https://github.com/simp/puppetlabs-stdlib
    svckill: https://github.com/simp/pupmod-simp-svckill
    yumrepo_core:
      repo: https://github.com/simp/pupmod-puppetlabs-yumrepo_core.git
      puppet_version: ">= 6.0.0"

    # Fixtures required for the acceptance tests
    simp_openldap: https://github.com/simp/pupmod-simp-simp_openldap
  symlinks:
    simp_gitlab: "#{source_dir}"
