---
fixtures:
  repositories:
    augeasproviders_core: https://github.com/simp/augeasproviders_core
    augeasproviders_ssh: https://github.com/simp/augeasproviders_ssh
    concat:
      # master is beyond 4.1.1, but has breaking changes to
      # how fragments are ordered (MODULES-6625)
      repo: https://github.com/simp/puppetlabs-concat
      ref: 4.1.1
    gitlab:
      repo: https://github.com/simp/puppet-gitlab.git
      ref: v1.13.3
    iptables: https://github.com/simp/pupmod-simp-iptables
    ntpd: https://github.com/simp/pupmod-simp-ntpd
    pam: https://github.com/simp/pupmod-simp-pam
    pki: https://github.com/simp/pupmod-simp-pki
    postfix: https://github.com/simp/pupmod-simp-postfix
    rsyslog: https://github.com/simp/pupmod-simp-rsyslog
    ssh: https://github.com/simp/pupmod-simp-ssh
    simplib: https://github.com/simp/pupmod-simp-simplib
    stdlib: https://github.com/simp/puppetlabs-stdlib
    svckill: https://github.com/simp/pupmod-simp-svckill

    # Fixtures required for the acceptance tests
    # auditd: https://github.com/simp/pupmod-simp-auditd
    # haveged: https://github.com/simp/pupmod-simp-haveged
    # logrotate: https://github.com/simp/pupmod-simp-logrotate
    # simp_openldap: https://github.com/simp/pupmod-simp-simp_openldap
    # simp_options: https://github.com/simp/pupmod-simp-simp_options
    # simpcat: https://github.com/simp/pupmod-simp-simpcat
    # tcpwrappers: https://github.com/simp/pupmod-simp-tcpwrappers
  symlinks:
    simp_gitlab: "#{source_dir}"
