---
fixtures:
  repositories:
    augeas_core: https://github.com/simp/pupmod-puppetlabs-augeas_core.git
    augeasproviders_core: https://github.com/simp/augeasproviders_core.git
    augeasproviders_ssh: https://github.com/simp/augeasproviders_ssh.git
    chrony: https://github.com/simp/pupmod-voxpupuli-chrony.git
    concat: https://github.com/simp/puppetlabs-concat.git
    ds389: https://github.com/simp/pupmod-simp-ds389.git
    firewalld: https://github.com/simp/pupmod-voxpupuli-firewalld.git
    gitlab: https://github.com/simp/puppet-gitlab.git
    iptables: https://github.com/simp/pupmod-simp-iptables.git
    pam: https://github.com/simp/pupmod-simp-pam.git
    pki: https://github.com/simp/pupmod-simp-pki.git
    postfix: https://github.com/simp/pupmod-simp-postfix.git
    rsyslog: https://github.com/simp/pupmod-simp-rsyslog.git
    ssh: https://github.com/simp/pupmod-simp-ssh.git
    simplib: https://github.com/simp/pupmod-simp-simplib.git
    simp_ds389: https://github.com/simp/pupmod-simp-simp_ds389.git
    simp_firewalld: https://github.com/simp/pupmod-simp-simp_firewalld.git
    stdlib: https://github.com/simp/puppetlabs-stdlib.git
    svckill: https://github.com/simp/pupmod-simp-svckill.git
    yumrepo_core: https://github.com/simp/pupmod-puppetlabs-yumrepo_core.git
    simp_openldap: https://github.com/simp/pupmod-simp-simp_openldap.git
  symlinks:
    simp_gitlab: "#{source_dir}"
